# Generated by Django 3.2.9 on 2021-11-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='pictures')),
                ('desc', models.TextField(max_length=200)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
