# Generated by Django 3.2.9 on 2021-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
